AllCops:
  # Include common Ruby source files.
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'vendor/**/*'

  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*

Metrics/LineLength:
  Max: 100

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  MinBodyLength: 3

Style/Lambda:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/StringLiterals:
  Enabled: false
